name: Merge notification
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Notify to Slack
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"test message, merged to main"}' ${{ secrets.WEBHOOK_KEY }}

      - name: Notify to Slack Test
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"test message"}' ${{ secrets.WEBHOOK_KEY }}